use serde::{Deserialize, Serialize};

/// One pipe/HOLDER PER PANE (not per profile) — see `project_som_tmux`
/// memory, "Обновление 17": the earlier design multiplexed several panes'
/// sessions over one profile-wide pipe using a `session_id` field inside
/// every message. That's gone now — since `som-tmux` no longer
/// speaks a structured protocol to Som at all (it's a transparent ANSI
/// relay, see `crate::redraw`), there's no client-side session registry
/// to multiplex against either. `pane_id` is generated by Som itself
/// (before ever spawning `som-tmux`) and passed as a `--pane-id`
/// argument, the same way on both first creation and restore — the server
/// never invents an id and hands it back the way it used to with
/// `SessionCreated`. `pane_id` (a UUID) is globally unique on its own, so
/// the pipe name doesn't need the profile name folded in for uniqueness —
/// it's kept as a parameter anyway purely so pipe names stay
/// human-readable in diagnostics (`tasklist`/`ls` on the socket directory).
///
/// Platform-specific shape: Windows named pipes live in a flat global
/// namespace (`\\.\pipe\...`), no directory involved. Unix domain sockets
/// are actual filesystem paths, so this creates (and reuses) a directory
/// under the system temp dir — mirroring where a real tmux/screen puts
/// their sockets (`$TMPDIR/tmux-<uid>/...`) rather than inventing a new
/// convention.
#[cfg(windows)]
pub fn pipe_name(profile_name: &str, pane_id: &str) -> String {
    let sanitize = |s: &str| -> String {
        s.chars()
            .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
            .collect()
    };
    format!(r"\\.\pipe\som-tmux-{}-{}", sanitize(profile_name), sanitize(pane_id))
}

/// `sockaddr_un::sun_path` is capped at 104-108 bytes depending on platform
/// (confirmed the hard way: a real HOLDER on macOS failed to bind with
/// "path must be shorter than SUN_LEN" — see `project_som_tmux` memory,
/// "Обновление 30"). `std::env::temp_dir()` (`$TMPDIR`) is the culprit on
/// macOS specifically: it resolves to a long per-user, per-boot path like
/// `/var/folders/4s/pl2zb02x33d63gxk15l1yvf00000gn/T/` (~47 bytes on its
/// own, versus Linux's plain `/tmp`, 5 bytes) — add `som-tmux-<uid>/` plus a
/// profile name and a 36-byte `pane_id` UUID and it overflows easily. Real
/// tmux sidesteps this the same way: it hardcodes `/tmp/tmux-<uid>/`,
/// ignoring `$TMPDIR` entirely, which is what this does too now.
#[cfg(unix)]
pub fn pipe_name(profile_name: &str, pane_id: &str) -> String {
    use std::hash::{Hash, Hasher};

    let sanitize = |s: &str| -> String {
        s.chars()
            .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
            .collect()
    };
    let dir = std::path::Path::new("/tmp").join(format!("som-tmux-{}", unsafe { libc::getuid() }));
    let _ = std::fs::create_dir_all(&dir);

    // Even under `/tmp`, a long `profile_name` plus a full UUID `pane_id`
    // can still overflow `SUN_LEN` once `dir` above is folded in — hash
    // both down to a short, fixed-width, still-unique-enough hex suffix
    // rather than trying to guess a length budget that depends on `dir`'s
    // own (platform-varying) length. Not cryptographic; collision risk is
    // irrelevant here (a same-machine, same-user socket path only ever
    // needs to avoid ACCIDENTAL collisions between concurrently open panes,
    // not resist an adversary).
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    profile_name.hash(&mut hasher);
    pane_id.hash(&mut hasher);
    let short_id = format!("{:016x}", hasher.finish());

    let sanitized_profile = sanitize(profile_name);
    let truncated_profile: String = sanitized_profile.chars().take(16).collect();
    dir.join(format!("{truncated_profile}-{short_id}.sock")).to_string_lossy().into_owned()
}

/// Which OS a HOLDER is running on — part of the handshake (see
/// `HandshakeInfo`) so a RELAY (potentially a newer build than the HOLDER
/// it's reattaching to, e.g. after Som updated but a remote HOLDER survived
/// from before) can tell whether they're even compatible before trusting
/// anything else about the connection. Deliberately only the four
/// combinations `project_som_tmux` memory ("Обновление 21") says are
/// actually supported — Intel Mac and Windows-on-ARM are excluded on
/// purpose ("пока не поддерживается" — not supported YET, not a permanent
/// decision, just nothing to detect or build for right now).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Os {
    Windows,
    Darwin,
    Linux,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Arch {
    Amd64,
    Arm64,
}

/// Detects the CURRENT process's own OS/architecture — used by both sides
/// to fill in their half of the handshake. `cfg!` rather than
/// `std::env::consts::{OS,ARCH}` string-matching, since those give runtime
/// strings ("windows", "aarch64") that would need re-parsing into this enum
/// anyway, and the actual platform is a compile-time fact for a given
/// binary.
pub fn current_platform() -> (Os, Arch) {
    let os = if cfg!(target_os = "windows") {
        Os::Windows
    } else if cfg!(target_os = "macos") {
        Os::Darwin
    } else {
        Os::Linux
    };
    let arch = if cfg!(target_arch = "x86_64") { Arch::Amd64 } else { Arch::Arm64 };
    (os, arch)
}

/// Exchanged first thing on every new connection, before any actual
/// terminal data — see `project_som_tmux` memory ("Обновление 19"/"21") for
/// the full policy this feeds into (always copy a newer binary over an
/// older one on disk; only ever restart a LIVE, already-running HOLDER
/// process if none of its panes have live child processes). This type only
/// carries the raw facts (version string, OS, arch) — the actual
/// version-compare/restart-or-not DECISION lives in `crate::relay`, not
/// here, since it needs additional context (e.g. "is the shell busy") this
/// protocol module has no business knowing about.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HandshakeInfo {
    /// `env!("CARGO_PKG_VERSION")` at build time — compared as a plain
    /// string, not semver-parsed: any difference at all (not just a
    /// semver-incompatible one) is treated as "different build, evaluate
    /// whether to update" by the policy in `crate::relay`, since this
    /// binary doesn't follow a public semver contract with itself.
    pub version: String,
    pub os: Os,
    pub arch: Arch,
}

impl HandshakeInfo {
    pub fn current() -> Self {
        let (os, arch) = current_platform();
        Self { version: env!("CARGO_PKG_VERSION").to_string(), os, arch }
    }
}

/// RELAY -> HOLDER: input coming from Som's own PTY (whatever the user
/// typed) gets forwarded verbatim, plus the couple of control events a
/// terminal needs to convey out-of-band from plain bytes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RelayInput {
    /// Always the FIRST message a RELAY sends on a fresh connection, before
    /// anything else — see `HandshakeInfo`'s doc comment. The HOLDER
    /// replies in kind with `HolderOutput::Handshake` before its first
    /// redraw.
    Handshake(HandshakeInfo),
    /// Raw bytes read from Som's side of the RELAY's own PTY — keystrokes,
    /// paste, anything the user's terminal client sends. Forwarded
    /// byte-for-byte into the real shell's PTY on the HOLDER side.
    Bytes(Vec<u8>),
    Resize { cols: u16, rows: u16 },
    /// Explicit "tab closed via UI" — kills the real shell process for
    /// good, as opposed to the RELAY simply disconnecting (which leaves
    /// the HOLDER and its shell running for a later reattach). Mirrors the
    /// detach-vs-kill semantics from the old protocol's `CloseSession`.
    Close,
}

/// HOLDER -> RELAY: v3 architecture (see `SOM_MUX_PLAN.md`'s "som-tmux v3"
/// section) — the HOLDER owns a headless `alacritty_terminal::Term` that
/// mirrors the real shell's actual terminal state (fed by the real PTY's
/// output through the normal ANSI parser), and sends that STATE to the
/// RELAY rather than diffing/replaying ANSI bytes (what v1's `redraw.rs`
/// did, and the specific design flaw this replaces: diffing visible grid
/// content structurally cannot carry terminal MODES like DECCKM, since a
/// mode flip has no visible content of its own).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum HolderOutput {
    /// Always the FIRST message a HOLDER sends back on a fresh connection,
    /// replying to the RELAY's own `RelayInput::Handshake` — see
    /// `HandshakeInfo`'s doc comment.
    Handshake(HandshakeInfo),
    /// A bincode-encoded `alacritty_terminal::term::serialize::TermState`
    /// (`Term::snapshot()`'s return value) — sent as the SECOND message on
    /// every connection (right after the handshake), before anything else.
    /// The RELAY deserializes it and calls `Term::restore()` on its OWN
    /// local `Term` (the same one Som's `Terminal`/`TerminalView` already
    /// render), which sets the grid, cursor, and — critically — the FULL
    /// `TermMode` bitflags directly, correct from the very first frame
    /// after a (re)connect. No ANSI replay needed to reproduce a screen a
    /// RELAY missed while disconnected; the state itself just IS correct.
    Snapshot(Vec<u8>),
    /// Raw bytes read from the real shell's PTY, forwarded so the RELAY can
    /// feed them through the SAME `ansi::Processor::advance` path any
    /// ordinary (non-tmux) Som terminal already uses on its own local
    /// `Term` — this is what keeps that `Term` (already correctly
    /// initialized by the `Snapshot` above) live and up to date afterward.
    /// Unlike v1's `Bytes` variant, these are NOT already-diffed/
    /// reconstructed ANSI from a `Redrawer` — they're literally what the
    /// real shell wrote, same as `RelayInput::Bytes` already is for the
    /// opposite direction.
    Bytes(Vec<u8>),
    /// The real shell process exited — the RELAY should exit too (nothing
    /// left to proxy). Distinct from a HOLDER-initiated disconnect for any
    /// other reason (which the RELAY treats as "connection lost, nothing
    /// more to do" without necessarily needing to know why).
    ShellExited,
}

#[cfg(all(test, unix))]
mod tests {
    use super::*;

    /// `sockaddr_un::sun_path` is 104 bytes on macOS, 108 on Linux — this
    /// asserts against the SMALLER (macOS) limit so the same test protects
    /// both. Regression test for the real bug this fixed: a profile name
    /// plus a full UUID pane_id, joined under `/tmp/som-tmux-<uid>/`, used
    /// to overflow this easily (confirmed against a real Mac — see
    /// `project_som_tmux` memory, "Обновление 30").
    #[test]
    fn pipe_name_stays_within_sun_len_even_for_a_long_profile_name_and_a_full_uuid_pane_id() {
        const MACOS_SUN_LEN: usize = 104;
        let long_profile_name = "a-fairly-descriptive-profile-name-someone-might-actually-type";
        let pane_id = uuid::Uuid::new_v4().to_string();

        let path = pipe_name(long_profile_name, &pane_id);

        assert!(
            path.len() < MACOS_SUN_LEN,
            "pipe_name produced a {}-byte path (>= the {MACOS_SUN_LEN}-byte SUN_LEN limit): {path:?}",
            path.len()
        );
    }

    #[test]
    fn pipe_name_is_stable_and_unique_per_profile_and_pane_id_pair() {
        let a = pipe_name("profile-a", "pane-1");
        let b = pipe_name("profile-a", "pane-1");
        let c = pipe_name("profile-a", "pane-2");
        let d = pipe_name("profile-b", "pane-1");

        assert_eq!(a, b, "same inputs must always produce the same path (RELAY and HOLDER compute it independently)");
        assert_ne!(a, c, "different pane_id must produce a different path");
        assert_ne!(a, d, "different profile_name must produce a different path");
    }
}
