use serde::{Deserialize, Serialize};

/// One pipe/HOLDER PER PANE (not per profile) — see `project_som_tmux`
/// memory, "Обновление 17": the earlier design multiplexed several panes'
/// sessions over one profile-wide pipe using a `session_id` field inside
/// every message. That's gone now — since `som-tmux` no longer
/// speaks a structured protocol to Som at all (it's a transparent ANSI
/// relay, see `crate::redraw`), there's no client-side session registry
/// to multiplex against either. `pane_id` is generated by Som itself
/// (before ever spawning `som-tmux`) and passed as a `--pane-id`
/// argument, the same way on both first creation and restore — the server
/// never invents an id and hands it back the way it used to with
/// `SessionCreated`. `pane_id` (a UUID) is globally unique on its own, so
/// the pipe name doesn't need the profile name folded in for uniqueness —
/// it's kept as a parameter anyway purely so pipe names stay
/// human-readable in diagnostics (`tasklist`/`ls` on the socket directory).
///
/// Platform-specific shape: Windows named pipes live in a flat global
/// namespace (`\\.\pipe\...`), no directory involved. Unix domain sockets
/// are actual filesystem paths, so this creates (and reuses) a directory
/// under the system temp dir — mirroring where a real tmux/screen puts
/// their sockets (`$TMPDIR/tmux-<uid>/...`) rather than inventing a new
/// convention.
#[cfg(windows)]
pub fn pipe_name(profile_name: &str, pane_id: &str) -> String {
    let sanitize = |s: &str| -> String {
        s.chars()
            .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
            .collect()
    };
    format!(r"\\.\pipe\som-tmux-{}-{}", sanitize(profile_name), sanitize(pane_id))
}

/// `sockaddr_un::sun_path` is capped at 104-108 bytes depending on platform
/// (confirmed the hard way: a real HOLDER on macOS failed to bind with
/// "path must be shorter than SUN_LEN" — see `project_som_tmux` memory,
/// "Обновление 30"). `std::env::temp_dir()` (`$TMPDIR`) is the culprit on
/// macOS specifically: it resolves to a long per-user, per-boot path like
/// `/var/folders/4s/pl2zb02x33d63gxk15l1yvf00000gn/T/` (~47 bytes on its
/// own, versus Linux's plain `/tmp`, 5 bytes) — add `som-tmux-<uid>/` plus a
/// profile name and a 36-byte `pane_id` UUID and it overflows easily. Real
/// tmux sidesteps this the same way: it hardcodes `/tmp/tmux-<uid>/`,
/// ignoring `$TMPDIR` entirely, which is what this does too now.
#[cfg(unix)]
pub fn pipe_name(profile_name: &str, pane_id: &str) -> String {
    use std::hash::{Hash, Hasher};

    let sanitize = |s: &str| -> String {
        s.chars()
            .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
            .collect()
    };
    let dir = std::path::Path::new("/tmp").join(format!("som-tmux-{}", unsafe { libc::getuid() }));
    let _ = std::fs::create_dir_all(&dir);

    // Even under `/tmp`, a long `profile_name` plus a full UUID `pane_id`
    // can still overflow `SUN_LEN` once `dir` above is folded in — hash
    // both down to a short, fixed-width, still-unique-enough hex suffix
    // rather than trying to guess a length budget that depends on `dir`'s
    // own (platform-varying) length. Not cryptographic; collision risk is
    // irrelevant here (a same-machine, same-user socket path only ever
    // needs to avoid ACCIDENTAL collisions between concurrently open panes,
    // not resist an adversary).
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    profile_name.hash(&mut hasher);
    pane_id.hash(&mut hasher);
    let short_id = format!("{:016x}", hasher.finish());

    let sanitized_profile = sanitize(profile_name);
    let truncated_profile: String = sanitized_profile.chars().take(16).collect();
    dir.join(format!("{truncated_profile}-{short_id}.sock")).to_string_lossy().into_owned()
}

/// `<remote-username>@<client-ip>` identifying BOTH the OS account that
/// SSHed into THIS host AND which machine it came from — the IP half comes
/// from sshd's own `$SSH_CLIENT`, the username half from THIS process's own
/// effective user (`whoami`-equivalent). Passed down through `--client-id`
/// on every RELAY-spawned HOLDER (see `main.rs`'s `Args`) so a HOLDER's
/// `ps` command line records who/what created it. Exists purely for orphan
/// cleanup and version-mismatch teardown: `kill_orphaned_holders`/
/// `kill_all_holders_for_redeploy` (`terminal_panel.rs`) run once per host
/// at handshake time (themselves a fresh `ssh host ...` invocation, so they
/// see their OWN `$SSH_CLIENT`/user, naturally equal to what any other
/// invocation from this same account on this same machine already got) and
/// must only ever touch HOLDERs they can actually judge "belongs to me or
/// not" — a HOLDER created by a DIFFERENT client machine, or a different
/// OS account on the SAME remote host (e.g. a shared build server with
/// several users each running their own Som), is invisible to this
/// account's own `db.json` and must never be treated as this account's to
/// kill, even though the raw `ps` listing sees it just fine. Comparing
/// `--client-id` against this very connection's own `<user>@$SSH_CLIENT`
/// needs no coordination between clients or accounts at all — sshd/the
/// remote OS already independently reports the same identity to every SSH
/// connection from the same account on the same machine.
///
/// Belt-and-suspenders on top of what Unix file/process permissions
/// already enforce (a non-privileged user's `kill` on another user's
/// process fails regardless) — this filter exists so a buggy cleanup query
/// simply never CONSIDERS another account's HOLDER a candidate in the
/// first place, rather than relying on the kill syscall to silently reject
/// it.
///
/// Only ever meaningful for an SSH `tmux: true` profile's RELAY (which
/// really does run ON the remote host, spawned via `ssh host
/// ~/.local/bin/som-tmux ...` — see `wrap_remote_command_args`) — `None`
/// for a local or WSL RELAY, neither of which goes through sshd and so has
/// no `$SSH_CLIENT` to read; `kill_orphaned_holders` only ever runs for
/// `RemoteKind::Ssh` anyway, so those callers simply never pass `--client-
/// id` at all.
pub fn ssh_client_id() -> Option<String> {
    let raw = std::env::var("SSH_CLIENT").ok()?;
    let ip = raw.split_whitespace().next()?;
    let user = whoami_unix()?;
    Some(format!("{user}@{ip}"))
}

#[cfg(unix)]
fn whoami_unix() -> Option<String> {
    // SAFETY: `geteuid()` has no failure mode (always returns the calling
    // process's real effective uid) and `getpwuid` on a valid uid returns
    // either a valid pointer into thread-local/static storage libc owns
    // (never freed by us, never mutated after return) or null — both
    // branches handled below.
    unsafe {
        let passwd = libc::getpwuid(libc::geteuid());
        if passwd.is_null() {
            return None;
        }
        let name = std::ffi::CStr::from_ptr((*passwd).pw_name);
        Some(name.to_string_lossy().into_owned())
    }
}

#[cfg(not(unix))]
fn whoami_unix() -> Option<String> {
    None
}

/// Which OS a HOLDER is running on — part of the handshake (see
/// `HandshakeInfo`) so a RELAY (potentially a newer build than the HOLDER
/// it's reattaching to, e.g. after Som updated but a remote HOLDER survived
/// from before) can tell whether they're even compatible before trusting
/// anything else about the connection. Deliberately only the four
/// combinations `project_som_tmux` memory ("Обновление 21") says are
/// actually supported — Intel Mac and Windows-on-ARM are excluded on
/// purpose ("пока не поддерживается" — not supported YET, not a permanent
/// decision, just nothing to detect or build for right now).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Os {
    Windows,
    Darwin,
    Linux,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Arch {
    Amd64,
    Arm64,
}

/// Detects the CURRENT process's own OS/architecture — used by both sides
/// to fill in their half of the handshake. `cfg!` rather than
/// `std::env::consts::{OS,ARCH}` string-matching, since those give runtime
/// strings ("windows", "aarch64") that would need re-parsing into this enum
/// anyway, and the actual platform is a compile-time fact for a given
/// binary.
pub fn current_platform() -> (Os, Arch) {
    let os = if cfg!(target_os = "windows") {
        Os::Windows
    } else if cfg!(target_os = "macos") {
        Os::Darwin
    } else {
        Os::Linux
    };
    let arch = if cfg!(target_arch = "x86_64") { Arch::Amd64 } else { Arch::Arm64 };
    (os, arch)
}

/// Directory name (under `platform_binaries_dir()`) holding the
/// pre-built `som-tmux` for a given `(Os, Arch)` pair — the names the user
/// chose for `~/.config/som/tmux/{name}/som-tmux`, one per (os, arch) pair
/// this codebase actually supports (see `Os`/`Arch`'s own doc comment for
/// the four supported combinations — Intel Mac and Windows-on-ARM are
/// excluded on purpose, so there is no `windows-arm`/`macos-amd` directory
/// to name). Used on BOTH ends of a deploy decision: locally, to find
/// which pre-built binary to `scp` up for a remote host reporting this
/// `(os, arch)` in its handshake; and (implicitly, by a human/release-
/// packaging script, not this codebase) to know where to drop each
/// cross-compiled build's output in the first place.
pub fn platform_dir_name(os: Os, arch: Arch) -> &'static str {
    match (os, arch) {
        (Os::Windows, Arch::Amd64) => "windows-amd",
        (Os::Darwin, Arch::Arm64) => "macos-arm",
        (Os::Linux, Arch::Amd64) => "linux-amd",
        (Os::Linux, Arch::Arm64) => "linux-arm",
        // Genuinely unsupported combos (Windows-on-ARM, Intel Mac) — no
        // directory name exists for these; `local_binary_path_for` never
        // finds a file regardless of what this string is, so any
        // placeholder is fine as long as it can never collide with a real
        // supported directory above.
        (Os::Windows, Arch::Arm64) => "windows-arm-unsupported",
        (Os::Darwin, Arch::Amd64) => "macos-amd-unsupported",
    }
}

/// `~/.config/som/tmux/` — where Som keeps a pre-built `som-tmux` for
/// every supported remote platform (see `platform_dir_name`), so an SSH
/// `tmux: true` profile's deploy step is a plain `scp` of an
/// already-built file rather than a `git pull && cargo build` on the
/// remote machine itself (see `project_som_tmux` memory for why that
/// changed: a build on every real target machine was the ORIGINAL
/// approach, explicitly chosen over cross-compilation at the time — this
/// supersedes that decision now that shipping pre-built binaries inside
/// Som's own installer for each platform is possible). Lives under Som's
/// own `paths::config_dir()`, same as `db.json` and everything else Som
/// persists locally — NOT a per-remote-host location; this directory is
/// read locally on the machine actually running Som, one entry per remote
/// platform Som might ever need to talk to, not per host.
pub fn platform_binaries_dir() -> std::path::PathBuf {
    paths::config_dir().join("tmux")
}

/// `som-tmux[.exe]` — the file name (not path) `local_binary_path_for`/
/// `ensure_embedded_binary_extracted` both use under a platform's own
/// `platform_dir_name` subdirectory.
fn binary_file_name(os: Os) -> &'static str {
    if let Os::Windows = os { "som-tmux.exe" } else { "som-tmux" }
}

/// Full local path to the pre-built `som-tmux` for a given remote
/// `(Os, Arch)` — `None` if Som has never been told about (or hasn't yet
/// downloaded/copied in) a binary for that platform. Callers (`terminal_
/// view`'s `ensure_remote_binary_deployed`) treat a missing file the same
/// way as an unreachable host: log and skip, rather than failing the tab.
pub fn local_binary_path_for(os: Os, arch: Arch) -> Option<std::path::PathBuf> {
    let path = platform_binaries_dir().join(platform_dir_name(os, arch)).join(binary_file_name(os));
    path.is_file().then_some(path)
}

/// Ensures the embedded `som-tmux` binary for a remote `(Os, Arch)` is
/// present and current at `platform_binaries_dir()`'s own path for that
/// platform, extracting `embedded_bytes` (Som's own RustEmbed'd copy — see
/// `crates/assets/src/assets.rs`'s `#[include = "tmux/..."]` entries) there
/// if the file is missing OR its own `--version` doesn't match
/// `embedded_version` (`env!("CARGO_PKG_VERSION")` at Som's build time,
/// same string `HandshakeInfo` already compares against a REMOTE host's
/// binary — this is the identical check, just run locally as a plain child
/// process instead of over SSH).
///
/// Returns the (now guaranteed-current, if `Some`) local path — the same
/// path `local_binary_path_for` would return once this has run — or `None`
/// if `embedded_bytes` is `None` (an unsupported platform: linux-arm,
/// windows-arm, or macos-amd; Som was never built with a binary for that
/// combination in the first place). Callers treat `None` exactly like
/// `local_binary_path_for`'s `None` already was: log and fall back to
/// plain (non-tmux) behavior for that profile, no crash.
///
/// This never touches a REMOTE host's binary — that overwrite-a-possibly-
/// running-process concern (`ETXTBSY`, kill-before-scp) belongs entirely to
/// `ensure_remote_binary_deployed` on the Som side. This function only
/// ever writes to Som's own local cache directory, which nothing else runs
/// out of directly.
pub fn ensure_embedded_binary_extracted(
    os: Os,
    arch: Arch,
    embedded_bytes: Option<&[u8]>,
    embedded_version: &str,
) -> Option<std::path::PathBuf> {
    let path = platform_binaries_dir().join(platform_dir_name(os, arch)).join(binary_file_name(os));
    ensure_embedded_binary_extracted_at(&path, embedded_bytes, embedded_version)
}

/// The actual extraction logic behind `ensure_embedded_binary_extracted`,
/// taking the target path directly rather than deriving it from
/// `platform_binaries_dir()` — split out so tests can point it at a
/// throwaway temp path instead of Som's real `~/.config/som/tmux/`.
fn ensure_embedded_binary_extracted_at(
    path: &std::path::Path,
    embedded_bytes: Option<&[u8]>,
    embedded_version: &str,
) -> Option<std::path::PathBuf> {
    let embedded_bytes = embedded_bytes?;

    if local_binary_version(path).as_deref() == Some(embedded_version) {
        return Some(path.to_path_buf());
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).ok()?;
    }
    std::fs::write(path, embedded_bytes).ok()?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755)).ok()?;
    }
    Some(path.to_path_buf())
}

/// Runs `path --version` (the same handshake-JSON probe `ensure_remote_
/// binary_deployed` already runs over SSH against a remote binary, here
/// invoked as a local child process instead) and returns just its version
/// string, or `None` if the file doesn't exist, isn't executable, or
/// doesn't understand `--version` (e.g. a corrupted/truncated download —
/// treated as "needs re-extracting", same as a missing file).
fn local_binary_version(path: &std::path::Path) -> Option<String> {
    if !path.is_file() {
        return None;
    }
    let output = std::process::Command::new(path).arg("--version").output().ok()?;
    if !output.status.success() {
        return None;
    }
    let stdout = String::from_utf8(output.stdout).ok()?;
    serde_json::from_str::<HandshakeInfo>(stdout.trim()).ok().map(|info| info.version)
}

/// Exchanged first thing on every new connection, before any actual
/// terminal data — see `project_som_tmux` memory ("Обновление 19"/"21") for
/// the full policy this feeds into (always copy a newer binary over an
/// older one on disk; only ever restart a LIVE, already-running HOLDER
/// process if none of its panes have live child processes). This type only
/// carries the raw facts (version string, OS, arch) — the actual
/// version-compare/restart-or-not DECISION lives in `crate::relay`, not
/// here, since it needs additional context (e.g. "is the shell busy") this
/// protocol module has no business knowing about.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HandshakeInfo {
    /// `env!("CARGO_PKG_VERSION")` at build time — compared as a plain
    /// string, not semver-parsed: any difference at all (not just a
    /// semver-incompatible one) is treated as "different build, evaluate
    /// whether to update" by the policy in `crate::relay`, since this
    /// binary doesn't follow a public semver contract with itself.
    pub version: String,
    pub os: Os,
    pub arch: Arch,
}

impl HandshakeInfo {
    pub fn current() -> Self {
        let (os, arch) = current_platform();
        Self { version: env!("CARGO_PKG_VERSION").to_string(), os, arch }
    }
}

/// RELAY -> HOLDER: input coming from Som's own PTY (whatever the user
/// typed) gets forwarded verbatim, plus the couple of control events a
/// terminal needs to convey out-of-band from plain bytes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RelayInput {
    /// Always the FIRST message a RELAY sends on a fresh connection, before
    /// anything else — see `HandshakeInfo`'s doc comment. The HOLDER
    /// replies in kind with `HolderOutput::Handshake` before its first
    /// redraw.
    Handshake(HandshakeInfo),
    /// Raw bytes read from Som's side of the RELAY's own PTY — keystrokes,
    /// paste, anything the user's terminal client sends. Forwarded
    /// byte-for-byte into the real shell's PTY on the HOLDER side.
    Bytes(Vec<u8>),
    Resize { cols: u16, rows: u16 },
    /// Explicit "tab closed via UI" — kills the real shell process for
    /// good, as opposed to the RELAY simply disconnecting (which leaves
    /// the HOLDER and its shell running for a later reattach). Mirrors the
    /// detach-vs-kill semantics from the old protocol's `CloseSession`.
    Close,
}

/// HOLDER -> RELAY: the HOLDER owns a headless `alacritty_terminal::Term`
/// that mirrors the real shell's actual terminal state (fed by the real
/// PTY's output through the normal ANSI parser), and sends that STATE to
/// the RELAY rather than diffing/replaying ANSI bytes — diffing visible
/// grid content structurally cannot carry terminal MODES like DECCKM, since
/// a mode flip has no visible content of its own.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum HolderOutput {
    /// Always the FIRST message a HOLDER sends back on a fresh connection,
    /// replying to the RELAY's own `RelayInput::Handshake` — see
    /// `HandshakeInfo`'s doc comment.
    Handshake(HandshakeInfo),
    /// A bincode-encoded `alacritty_terminal::term::serialize::TermState`
    /// (`Term::snapshot()`'s return value) — sent as the SECOND message on
    /// every connection (right after the handshake), before anything else.
    /// The RELAY deserializes it and calls `Term::restore()` on its OWN
    /// local `Term` (the same one Som's `Terminal`/`TerminalView` already
    /// render), which sets the grid, cursor, and — critically — the FULL
    /// `TermMode` bitflags directly, correct from the very first frame
    /// after a (re)connect. No ANSI replay needed to reproduce a screen a
    /// RELAY missed while disconnected; the state itself just IS correct.
    Snapshot(Vec<u8>),
    /// Raw bytes read from the real shell's PTY, forwarded so the RELAY can
    /// feed them through the SAME `ansi::Processor::advance` path any
    /// ordinary (non-tmux) Som terminal already uses on its own local
    /// `Term` — this is what keeps that `Term` (already correctly
    /// initialized by the `Snapshot` above) live and up to date afterward.
    /// These are NOT diffed/reconstructed ANSI from a `Redrawer` — they're
    /// literally what the real shell wrote, same as `RelayInput::Bytes`
    /// already is for the opposite direction.
    Bytes(Vec<u8>),
    /// The real shell process exited — the RELAY should exit too (nothing
    /// left to proxy). Distinct from a HOLDER-initiated disconnect for any
    /// other reason (which the RELAY treats as "connection lost, nothing
    /// more to do" without necessarily needing to know why).
    ShellExited,
}

#[cfg(test)]
mod platform_dir_tests {
    use super::*;

    /// Regression coverage for a real naming ambiguity: `platform_dir_name`
    /// used to map EVERY `Os::Windows` to a bare `"windows"` and every
    /// `Os::Darwin` to a bare `"macos"`, ignoring `Arch` entirely — fine by
    /// accident today (only one arch per OS is actually supported, see
    /// `Os`/`Arch`'s own doc comment), but the name alone gave no way to
    /// tell whether a given directory held an amd64 or arm64 build.
    /// Renamed to always carry the arch suffix, matching `linux-amd`/
    /// `linux-arm`'s existing convention, so `~/.config/som/tmux/`'s
    /// directory names are self-describing regardless of which two of the
    /// four supported combos anyone's actually using.
    #[test]
    fn windows_amd64_maps_to_windows_amd() {
        assert_eq!(platform_dir_name(Os::Windows, Arch::Amd64), "windows-amd");
    }

    #[test]
    fn macos_arm64_maps_to_macos_arm() {
        // The real Mac this codebase talks to (see project_som_tmux
        // memory) is Apple Silicon (arm64) — Intel Mac is explicitly
        // unsupported (Os/Arch's own doc comment), so this is the only
        // Darwin combo that should ever resolve to a real directory.
        assert_eq!(platform_dir_name(Os::Darwin, Arch::Arm64), "macos-arm");
    }

    #[test]
    fn linux_amd64_maps_to_linux_amd() {
        assert_eq!(platform_dir_name(Os::Linux, Arch::Amd64), "linux-amd");
    }

    #[test]
    fn linux_arm64_maps_to_linux_arm() {
        assert_eq!(platform_dir_name(Os::Linux, Arch::Arm64), "linux-arm");
    }

    #[test]
    fn every_supported_combo_maps_to_a_distinct_directory_name() {
        // The four combos project_som_tmux memory ("Обновление 21") says
        // are actually supported — Intel Mac and Windows-on-ARM excluded
        // on purpose, deliberately not asserted here at all.
        let supported = [
            (Os::Windows, Arch::Amd64),
            (Os::Darwin, Arch::Arm64),
            (Os::Linux, Arch::Amd64),
            (Os::Linux, Arch::Arm64),
        ];
        let names: Vec<&str> = supported.iter().map(|&(os, arch)| platform_dir_name(os, arch)).collect();
        for (i, a) in names.iter().enumerate() {
            for (j, b) in names.iter().enumerate() {
                if i != j {
                    assert_ne!(a, b, "two supported (os, arch) combos must never share a directory name: {supported:?}");
                }
            }
        }
    }

    #[test]
    fn current_platform_always_resolves_to_a_supported_combo() {
        // Whatever machine actually runs this test, current_platform()'s
        // own (os, arch) result must itself be one of the four supported
        // combos — otherwise Som's own build platform wouldn't even be
        // able to name its own directory under ~/.config/som/tmux/.
        let (os, arch) = current_platform();
        let supported = matches!(
            (os, arch),
            (Os::Windows, Arch::Amd64) | (Os::Darwin, Arch::Arm64) | (Os::Linux, Arch::Amd64) | (Os::Linux, Arch::Arm64)
        );
        assert!(supported, "current_platform() returned an unsupported combo: {os:?}/{arch:?}");
    }

    #[test]
    fn local_binary_path_for_uses_the_exe_suffix_only_on_windows() {
        // Doesn't touch the filesystem (no real file exists at this
        // fabricated config_dir in a test environment) — local_binary_
        // path_for returns None either way, but the file NAME it would
        // have looked for is what this test actually protects (the .exe
        // suffix decision), so this reaches into platform_binaries_dir()
        // directly rather than trying to assert on local_binary_path_for's
        // None result.
        let windows_dir = platform_binaries_dir().join(platform_dir_name(Os::Windows, Arch::Amd64));
        let unix_dir = platform_binaries_dir().join(platform_dir_name(Os::Linux, Arch::Amd64));
        assert!(windows_dir.ends_with("windows-amd"));
        assert!(unix_dir.ends_with("linux-amd"));
    }

    #[test]
    fn local_binary_path_for_returns_none_when_no_file_exists_for_that_platform() {
        // A platform combo whose directory almost certainly doesn't exist
        // in whatever environment runs this test (or if it does, has no
        // file in it) — must return None, not panic or fabricate a path
        // that doesn't actually exist on disk.
        let result = local_binary_path_for(Os::Linux, Arch::Arm64);
        // Can't assert None unconditionally — a dev machine that's ALSO
        // used to run the real deploy-som-tmux.sh script might genuinely
        // have this file. Only assert the contract that matters: if Some,
        // the path really does exist on disk.
        if let Some(path) = result {
            assert!(path.is_file(), "local_binary_path_for returned a path that doesn't actually exist: {path:?}");
        }
    }
}

#[cfg(test)]
mod embedded_binary_tests {
    use super::*;

    fn temp_path(name: &str) -> std::path::PathBuf {
        std::env::temp_dir().join(format!(
            "som_tmux_embedded_binary_test_{}_{name}",
            std::process::id()
        ))
    }

    #[test]
    fn missing_embedded_bytes_returns_none_without_touching_disk() {
        let path = temp_path("missing_bytes");
        let _ = std::fs::remove_file(&path);
        assert_eq!(ensure_embedded_binary_extracted_at(&path, None, "1.0.0"), None);
        assert!(!path.exists(), "must not create a file when embedded_bytes is None");
    }

    #[test]
    fn missing_local_file_gets_written_from_embedded_bytes() {
        let path = temp_path("missing_file");
        let _ = std::fs::remove_file(&path);
        let bytes = b"not a real binary, just test content";

        let result = ensure_embedded_binary_extracted_at(&path, Some(bytes), "1.0.0");

        assert_eq!(result.as_deref(), Some(path.as_path()));
        assert_eq!(std::fs::read(&path).unwrap(), bytes);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn a_file_that_fails_the_version_probe_gets_overwritten() {
        // Simulates a stale/corrupted extraction: `local_binary_version`
        // can't parse `--version` output from arbitrary garbage bytes (this
        // isn't even a real executable, so running it fails outright) —
        // same code path a genuinely OLDER som-tmux build would hit if its
        // version string just didn't match, both treated identically as
        // "needs re-extracting".
        let path = temp_path("garbage_content");
        std::fs::write(&path, b"garbage, not an executable").unwrap();
        let new_bytes = b"replacement content";

        let result = ensure_embedded_binary_extracted_at(&path, Some(new_bytes), "1.0.0");

        assert_eq!(result.as_deref(), Some(path.as_path()));
        assert_eq!(std::fs::read(&path).unwrap(), new_bytes);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn a_binary_reporting_the_matching_version_is_left_untouched() {
        // Uses the REAL locally-built som-tmux (this very test binary's own
        // sibling artifact) so `--version` genuinely succeeds and reports a
        // real, parseable HandshakeInfo — the one case that must NOT
        // rewrite the file (mirrors ensure_remote_binary_deployed's own
        // "already up to date, nothing to do" early return for a remote
        // host).
        let Ok(current_exe) = std::env::current_exe() else { return };
        let Some(deps_dir) = current_exe.parent() else { return };
        let Some(profile_dir) = deps_dir.parent() else { return };
        let candidate = profile_dir.join(if cfg!(windows) { "som-tmux.exe" } else { "som-tmux" });
        if !candidate.is_file() {
            // Not every dev environment has built the som-tmux bin
            // alongside the test artifacts — skip rather than fail.
            return;
        }

        let real_version = HandshakeInfo::current().version;
        let path = temp_path("matching_version");
        std::fs::copy(&candidate, &path).unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755)).unwrap();
        }
        let original_bytes = std::fs::read(&path).unwrap();
        let modified_time_before = std::fs::metadata(&path).unwrap().modified().unwrap();

        std::thread::sleep(std::time::Duration::from_millis(20));
        let result = ensure_embedded_binary_extracted_at(&path, Some(b"should never be written"), &real_version);

        assert_eq!(result.as_deref(), Some(path.as_path()));
        assert_eq!(
            std::fs::read(&path).unwrap(),
            original_bytes,
            "a binary already reporting the matching version must not be rewritten"
        );
        assert_eq!(
            std::fs::metadata(&path).unwrap().modified().unwrap(),
            modified_time_before,
            "must not touch the file at all when the version already matches"
        );
        let _ = std::fs::remove_file(&path);
    }
}

#[cfg(all(test, unix))]
mod tests {
    use super::*;

    /// `sockaddr_un::sun_path` is 104 bytes on macOS, 108 on Linux — this
    /// asserts against the SMALLER (macOS) limit so the same test protects
    /// both. Regression test for the real bug this fixed: a profile name
    /// plus a full UUID pane_id, joined under `/tmp/som-tmux-<uid>/`, used
    /// to overflow this easily (confirmed against a real Mac — see
    /// `project_som_tmux` memory, "Обновление 30").
    #[test]
    fn pipe_name_stays_within_sun_len_even_for_a_long_profile_name_and_a_full_uuid_pane_id() {
        const MACOS_SUN_LEN: usize = 104;
        let long_profile_name = "a-fairly-descriptive-profile-name-someone-might-actually-type";
        let pane_id = uuid::Uuid::new_v4().to_string();

        let path = pipe_name(long_profile_name, &pane_id);

        assert!(
            path.len() < MACOS_SUN_LEN,
            "pipe_name produced a {}-byte path (>= the {MACOS_SUN_LEN}-byte SUN_LEN limit): {path:?}",
            path.len()
        );
    }

    #[test]
    fn pipe_name_is_stable_and_unique_per_profile_and_pane_id_pair() {
        let a = pipe_name("profile-a", "pane-1");
        let b = pipe_name("profile-a", "pane-1");
        let c = pipe_name("profile-a", "pane-2");
        let d = pipe_name("profile-b", "pane-1");

        assert_eq!(a, b, "same inputs must always produce the same path (RELAY and HOLDER compute it independently)");
        assert_ne!(a, c, "different pane_id must produce a different path");
        assert_ne!(a, d, "different profile_name must produce a different path");
    }
}
