//! RELAY side of the transparent-PTY-proxy architecture — see
//! `project_som_tmux` memory ("Обновление 16"-19) for the full design.
//!
//! This is the thin process Som itself spawns directly into its own PTY:
//! from Som's point of view it's just "the shell command" for a `tmux:
//! true` profile — Som's `TerminalElement`/`TerminalView` are completely
//! unaware anything unusual is happening. This process's own stdin/stdout
//! ARE the PTY Som created for it. It connects to the long-lived HOLDER
//! (spawning one if none exists yet for this pane) over a named pipe and
//! simply shuttles bytes: whatever Som's PTY sends on this process's stdin
//! (keystrokes) goes to the HOLDER as `RelayInput::Bytes`; whatever the
//! HOLDER sends back (`HolderOutput::Bytes`, plain ANSI generated by
//! `crate::redraw`) gets written straight to this process's own stdout,
//! which is what Som's terminal parser actually reads.

use alacritty_terminal::event::VoidListener;
use alacritty_terminal::term::{Config, Term};
use anyhow::Context as _;
use som_tmux::pipe::PipeConnection;
use som_tmux::protocol::{HandshakeInfo, HolderOutput, RelayInput, pipe_name};
use std::io::{Read, Write};
use std::sync::{Arc, Mutex};
use std::time::Duration;

const CONNECT_RETRY_ATTEMPTS: u32 = 20;
const CONNECT_RETRY_DELAY: Duration = Duration::from_millis(100);

/// How many consecutive identical readings of `term_size::current_size()`
/// are required before treating it as "settled" (see `settled_initial_size`'s
/// doc comment) — 2 is enough to reject a single stale reading, without
/// making a genuinely-still-changing size (a real drag-resize in progress)
/// wait indefinitely for a quiet moment that current_size polling any
/// faster than this would still eventually see.
const SETTLE_STABLE_READS_REQUIRED: u32 = 2;
const SETTLE_POLL_INTERVAL: Duration = Duration::from_millis(20);
/// 150 * 20ms = 3s worst case — a WSL profile's PTY goes through an extra
/// Windows ConPTY -> wsl.exe -> Linux pty translation hop that can keep it
/// stuck at the placeholder size (see `PLACEHOLDER_SIZE`) noticeably longer
/// than a local Windows profile's first GPUI layout pass takes, so this
/// needs real headroom rather than a count tuned for the common (local)
/// case.
const SETTLE_MAX_ATTEMPTS: u32 = 150;

/// `TerminalBounds::default()`'s placeholder size (`DEBUG_TERMINAL_WIDTH` /
/// `DEBUG_TERMINAL_HEIGHT` in `crates/terminal/src/terminal.rs`, 500px/5px
/// and 30px/5px respectively) — a PTY sitting at exactly this size means
/// Som's real GPUI layout for this pane almost certainly hasn't run yet,
/// REGARDLESS of how many consecutive reads agree on it. Confirmed for WSL
/// profiles specifically: the extra Windows ConPTY -> wsl.exe -> Linux pty
/// translation hop adds enough latency that this placeholder can stay put
/// for well over what a short fixed iteration count would tolerate, which
/// used to make `settled_initial_size` treat the placeholder itself as
/// "stable" and confidently report the wrong size.
const PLACEHOLDER_SIZE: (u16, u16) = (100, 6);

/// Polls `term_size::current_size()` repeatedly until two consecutive reads
/// agree on something other than `PLACEHOLDER_SIZE` (or `SETTLE_MAX_WAIT`
/// elapses), instead of trusting the very first reading — see the call
/// site's doc comment for the full story, but in short: right when a RELAY
/// first connects (freshly spawned by Som, OR reattaching after
/// `restore_som_tabs`/a tab switch), Som's own `TerminalElement` for this
/// specific pane may not have gone through its first real GPUI layout pass
/// yet, so its PTY (and this RELAY's own console, sitting inside it) can
/// still be at `TerminalBounds::default()`'s placeholder size for a brief
/// moment before Som's real layout resizes it. Trusting that first reading
/// unconditionally (the original behavior) sent a HOLDER a wrong initial
/// size it then had to correct a moment later via the resize-poll thread —
/// visible to the user as a stray "flash" where a full-screen app like
/// `htop` briefly renders at the wrong (too-small, or previously-cached)
/// size before snapping to the right one. Confirmed root cause of a
/// reported bug: `htop` not filling the whole pane on Som restart/tab
/// switch until something else (a later real resize) corrected it — this
/// makes the CORRECT size available for the HOLDER's very first redraw
/// instead, removing the visible flash entirely.
///
/// If `SETTLE_MAX_WAIT` elapses without ever seeing anything other than
/// `PLACEHOLDER_SIZE`, falls back to whatever was last read anyway (even if
/// that's still the placeholder) — the resize-poll thread will still
/// eventually correct it, same as before this fix existed; this only makes
/// the COMMON case flash-free, not a hard guarantee for every possible
/// timing.
fn settled_initial_size() -> (u16, u16) {
    settle_from(SETTLE_MAX_ATTEMPTS, || {
        std::thread::sleep(SETTLE_POLL_INTERVAL);
        crate::term_size::current_size()
    })
}

/// The actual settle algorithm, factored out from `settled_initial_size` so
/// it can be tested without real sleeps or a real console — `read` blocks
/// for one polling interval and returns the next reading (called at most
/// once per loop iteration, exactly like the real one sleeping between
/// reads); `max_attempts` bounds the loop instead of a wall-clock deadline
/// so a test can exercise the "never stabilizes in time" path without
/// actually waiting.
fn settle_from(max_attempts: u32, mut read: impl FnMut() -> Option<(u16, u16)>) -> (u16, u16) {
    let mut last = read();
    let mut stable_reads = if last == Some(PLACEHOLDER_SIZE) { 0 } else { 1 };
    for _ in 0..max_attempts {
        if stable_reads >= SETTLE_STABLE_READS_REQUIRED {
            break;
        }
        let next = read();
        if next == Some(PLACEHOLDER_SIZE) {
            // Never counts toward stability, no matter how many times it
            // repeats — see `settled_initial_size`'s doc comment.
            stable_reads = 0;
            last = next;
            continue;
        }
        if next == last {
            stable_reads += 1;
        } else {
            stable_reads = 1;
            last = next;
        }
    }
    last.unwrap_or((80, 24))
}

/// Runs the RELAY: connects to (or spawns) the HOLDER for this pane, then
/// blocks for the lifetime of the connection, shuttling bytes both ways.
/// Returns once the HOLDER disconnects or the shell it holds exits — at
/// that point there's nothing left for this process to proxy, so `main`
/// just lets it exit (Som sees its PTY's child process end, same as any
/// other shell exiting).
pub fn run(
    profile_name: &str,
    pane_id: &str,
    program: String,
    args: Vec<String>,
    cwd: Option<String>,
    cursor_shape: Option<String>,
    scrollback: Option<usize>,
) -> anyhow::Result<()> {
    // See `term_size::enable_raw_input_mode`'s doc comment — without this,
    // Windows's OWN console input layer (`ReadConsoleW`, underneath this
    // process's `std::io::stdin()`) line-buffers and locally echoes every
    // keystroke completely independent of anything this crate does with the
    // bytes, which is the confirmed root cause of three separate reported
    // symptoms (line-buffered input needing an extra Enter, typed text
    // showing up in the console's leftover color instead of the shell's own
    // syntax-highlight color, and PSReadLine's live suggestions never
    // triggering). Called before anything else touches stdin.
    crate::term_size::enable_raw_input_mode();

    let connection = Arc::new(connect_or_become_holder(profile_name, pane_id, program, args, cwd, cursor_shape.clone(), scrollback)?);
    // Guards every `write_message` call on `connection` — the stdin-forwarding
    // loop (main thread) and the resize-polling thread both write
    // `RelayInput`s onto the SAME underlying pipe/socket handle, and
    // `write_message` is two separate writes (length prefix, then payload).
    // Without this, an unlucky interleaving between those two threads could
    // corrupt the framing (one thread's length prefix landing between the
    // other's prefix and payload) — confirmed as the root cause of a
    // reported ">>"-after-Enter artifact: a corrupted RelayInput::Bytes
    // frame can silently drop/mangle a keystroke (e.g. the Enter that ends
    // a command), leaving PowerShell's own PSReadLine thinking the command
    // is still incomplete and showing its real continuation prompt. Mirrors
    // `server.rs`'s own `writer: Arc<Mutex<()>>`, which already protects the
    // HOLDER's equivalent multi-writer situation (its main loop plus the
    // redraw-forwarder thread) — this was simply the one side that hadn't
    // needed it until the resize-polling thread (a second writer) was added.
    let writer = Arc::new(Mutex::new(()));

    // Handshake first, before anything else on this connection — see
    // `protocol::HandshakeInfo`'s doc comment. The relay speaks first here;
    // `crate::server::handle_relay` is the side that waits for it.
    //
    // What happens with a MISMATCHED version/platform: right now, just
    // logged, not acted on — this relay proxies to whatever holder answers
    // regardless. The actual "copy a newer binary over / restart a live
    // holder if none of its panes are busy" policy from `project_som_tmux`
    // memory ("Обновление 19"/"21") needs machinery this crate doesn't have
    // yet (comparing against Som's OWN bundled version, deciding whether to
    // overwrite a file out from under a running process, checking for live
    // child processes under the shell) — deliberately NOT bolted on here
    // half-finished; the handshake EXCHANGE is the prerequisite this adds,
    // the DECISION is future work.
    send(&connection, &writer, &RelayInput::Handshake(HandshakeInfo::current()))?;
    match read_holder_message(&connection)? {
        HolderOutput::Handshake(info) => {
            log::info!(
                "holder handshake: version={:?} os={:?} arch={:?}",
                info.version, info.os, info.arch
            );
        }
        other => anyhow::bail!("expected Handshake as the first message from a holder, got {other:?}"),
    }

    // Sends the current pane size right after the handshake, before
    // anything else — `crate::server::handle_relay` deliberately waits for
    // exactly this one message before its first full redraw (see that
    // function's doc comment), so a (re)attaching pane never has to visibly
    // jump from whatever size the session happened to be at to its actual
    // current size. Always sent (never skipped), even when `current_size()`
    // can't read a real size (falls back to `SessionBounds::default()`'s
    // 80x24) — the HOLDER unconditionally waits for exactly one message
    // here, so this side must unconditionally send exactly one.
    let initial_size = settled_initial_size();
    send(&connection, &writer, &RelayInput::Resize { cols: initial_size.0, rows: initial_size.1 })?;

    let reader_connection = connection.clone();
    // Config for the throwaway `Term` a `Snapshot` is restored onto below —
    // built with the profile's real cursor shape (from `--cursor-shape`),
    // NOT `Config::default()`. A restored `TermState` carries the grid and
    // the DYNAMIC cursor style (whatever the shell last set via DECSCUSR),
    // but a freshly-connected session's shell hasn't sent a DECSCUSR yet
    // (this host's does it from `PROMPT_COMMAND`, i.e. only once the first
    // prompt after an Enter is drawn), so `Term::cursor_style` is `None`
    // and `cursor_style()` falls back to `config.default_cursor_style`. If
    // that config default is `Config::default()`'s Block, the very first
    // frame draws a Block/bar cursor regardless of the configured shape,
    // only snapping to the right shape once the shell finally emits its own
    // DECSCUSR — confirmed as a reported bug (underline profile shows a bar
    // until the first Enter). Seeding the config with the real shape makes
    // the first frame already correct.
    let snapshot_term_config = Config {
        default_cursor_style: crate::session::parse_cursor_shape(cursor_shape.as_deref()),
        ..Config::default()
    };
    let writer_thread = std::thread::spawn(move || -> anyhow::Result<()> {
        loop {
            let message = read_holder_message(&reader_connection)?;
            match message {
                // This RELAY is a separate OS process from Som, not part
                // of the editor — the only way it can affect what Som's
                // own `Terminal`/`ansi::Processor` actually renders is by
                // writing plain ANSI bytes to its own stdout. So a
                // `Snapshot` still needs a one-time "state -> ANSI" step:
                // restore the bincode-decoded `TermState` onto a throwaway
                // local `Term` (used for nothing except this one
                // conversion), then run a SINGLE full-redraw pass over it
                // via a fresh `Redrawer` (whose very first `redraw()` call
                // is documented to always be a full, from-scratch repaint
                // — see `Redrawer::new`'s doc comment) and write those
                // bytes to stdout once. No further redraw calls happen
                // after this — subsequent `HolderOutput::Bytes` are
                // forwarded completely unmodified below.
                HolderOutput::Snapshot(encoded) => {
                    let (state, _): (alacritty_terminal::term::serialize::TermState, usize) =
                        bincode::serde::decode_from_slice(&encoded, bincode::config::standard())
                            .context("failed to decode HOLDER's TermState snapshot")?;
                    // Any starting size works — `Term::restore` replaces
                    // `self.grid` (and therefore its dimensions) wholesale
                    // with `state.grid`, so this placeholder never
                    // actually gets rendered against.
                    let placeholder_bounds = crate::bounds::SessionBounds::new(1, 1);
                    let mut term = Term::new(snapshot_term_config.clone(), &placeholder_bounds, VoidListener);
                    term.restore(state);

                    let mut redrawer = crate::redraw::Redrawer::new();
                    let mut bytes = Vec::new();
                    redrawer.redraw(&term, &mut bytes)?;
                    std::io::stdout().write_all(&bytes)?;
                    std::io::stdout().flush()?;
                }
                // The ongoing stream, post-snapshot: raw bytes straight
                // from the real shell's PTY (see `Session::subscribe_raw_
                // bytes`/`RawByteBroadcaster` on the HOLDER side) —
                // written through unmodified, exactly like a plain
                // (non-tmux) Som terminal's own PTY output already is.
                HolderOutput::Bytes(bytes) => {
                    std::io::stdout().write_all(&bytes)?;
                    std::io::stdout().flush()?;
                }
                HolderOutput::ShellExited => return Ok(()),
                // Only expected once, handled above before this loop
                // starts — a second one mid-connection is a protocol
                // violation from the holder, not something to crash the
                // whole relay over.
                HolderOutput::Handshake(_) => {
                    log::warn!("received an unexpected second Handshake mid-connection, ignoring it");
                }
            }
        }
    });

    // Polls this process's own stdout (Som's PTY, resized whenever Som
    // resizes the pane/window) for size changes and forwards them to the
    // HOLDER — see `crate::term_size`'s module doc comment for why this is
    // a poll rather than an event subscription, and `project_som_tmux`
    // memory ("Обновление 20") for why this was missing entirely before:
    // the HOLDER's session used to be permanently stuck at its initial
    // hardcoded 80x24, which is the root cause of both "the terminal
    // doesn't fill the pane" and (less obviously) stray-looking artifacts
    // after the shell scrolls, since Som's own `TerminalElement` renders at
    // the REAL pane size while every escape code the HOLDER generated was
    // computed against a completely different, wrong screen width.
    let resize_connection = connection.clone();
    let resize_writer = writer.clone();
    let resize_thread = std::thread::spawn(move || {
        // Seeded with the size already sent above, so this loop's first
        // tick doesn't immediately re-send an identical Resize.
        let mut last_size = initial_size;
        loop {
            std::thread::sleep(Duration::from_millis(250));
            let Some((cols, rows)) = crate::term_size::current_size() else { continue };
            if last_size == (cols, rows) {
                continue;
            }
            last_size = (cols, rows);
            if send(&resize_connection, &resize_writer, &RelayInput::Resize { cols, rows }).is_err() {
                return; // holder gone — writer_thread/stdin loop will notice too
            }
        }
    });

    // Reads Som's own PTY input (whatever the user types) off this
    // process's stdin and forwards it to the HOLDER. Runs on the main
    // thread/blocks `run` for as long as stdin stays open — Som closing
    // this process's PTY (the whole point of this being a normal PTY
    // child) naturally ends this loop via a read error/EOF.
    //
    // Strips a `\n` immediately following a `\r` before forwarding — see
    // `project_som_tmux` memory for the full writeup, but in short: this
    // process itself sits inside its OWN ConPTY (the one Som created for
    // it), and Windows' ConPTY normalizes a bare `\r` keystroke into `\r\n`
    // on ITS input side before this process's stdin ever sees it. A plain
    // (non-tmux) terminal only ever has ONE ConPTY layer between the user
    // and the real shell, so the real shell only ever sees that single,
    // already-normalized `\r\n` — completely normal, shells handle it fine.
    // This architecture's transparent-proxy design adds a SECOND ConPTY
    // layer (this RELAY's own, plus the HOLDER's separate one around the
    // real shell) — forwarding the already-normalized `\r\n` verbatim means
    // the real shell's ConPTY normalizes ITS `\r` again, but the leftover
    // `\n` from the FIRST normalization arrives as a second, distinct
    // keystroke immediately after. Confirmed root cause (real, isolated
    // repro, no IPC/HOLDER involved at all) of a reported PSReadLine
    // continuation-prompt (">>") artifact after pressing Enter on an empty
    // prompt — PSReadLine treats that leftover `\n` as its own "insert
    // newline" keystroke, not as part of the same Enter.
    let mut buf = [0u8; 4096];
    let mut last_byte_was_cr = false;
    loop {
        let read = match std::io::stdin().read(&mut buf) {
            Ok(0) => break, // EOF — Som closed its side
            Ok(n) => n,
            Err(_) => break,
        };
        // A lone NUL byte is `TerminalView::on_removed`'s explicit "the user
        // closed this tab, kill the real shell for good" signal — see that
        // function's doc comment for why this can't just be Som killing the
        // RELAY process directly (indistinguishable, on Windows especially,
        // from Som's own app-quit killing the SAME RELAY process the SAME
        // way, which must NOT kill the HOLDER). A real keyboard/paste never
        // produces a bare `\0` on its own, so this is unambiguous — checked
        // BEFORE the CRLF filter/forwarding below since it's a control
        // signal, not shell input to relay.
        if buf[..read].contains(&0u8) {
            send(&connection, &writer, &RelayInput::Close).ok();
            break;
        }
        let filtered = strip_cr_induced_lf(&buf[..read], &mut last_byte_was_cr);
        if filtered.is_empty() {
            continue;
        }
        if send(&connection, &writer, &RelayInput::Bytes(filtered)).is_err() {
            break; // holder gone
        }
    }

    // Best-effort: the writer thread's `read_message` will itself error
    // out once this relay's connection handle is dropped at the end of
    // `run` (stdin loop above already broke), so there's nothing more to
    // signal it — just let it wind down on its own rather than blocking
    // this function's return on `join()`. Same reasoning applies to the
    // resize-polling thread — its next `send()` fails once `connection` is
    // gone, ending its loop on its own.
    drop(writer_thread);
    drop(resize_thread);
    Ok(())
}

fn send(connection: &PipeConnection, writer: &Mutex<()>, message: &RelayInput) -> anyhow::Result<()> {
    let payload = serde_json::to_vec(message)?;
    let _guard = writer.lock().unwrap();
    connection.write_message(&payload)?;
    Ok(())
}

fn read_holder_message(connection: &PipeConnection) -> anyhow::Result<HolderOutput> {
    let message = connection.read_message()?;
    Ok(serde_json::from_slice(&message)?)
}

/// Tries to connect to an already-running HOLDER first; if nothing's
/// listening, becomes the HOLDER itself (spawns the real shell in-process
/// and starts serving the pipe) — but that means THIS process would need
/// to keep running as the HOLDER indefinitely, which contradicts it also
/// being Som's own PTY child (Som closing its window would end this
/// process along with the shell inside it, defeating the entire point of
/// detach/reattach). So instead: spawn a SEPARATE, detached process to
/// actually be the HOLDER (reusing the same binary with a `--holder` flag
/// — see `main.rs`), then connect to IT as a normal RELAY. This process
/// itself never becomes a HOLDER directly.
fn connect_or_become_holder(
    profile_name: &str,
    pane_id: &str,
    program: String,
    args: Vec<String>,
    cwd: Option<String>,
    cursor_shape: Option<String>,
    scrollback: Option<usize>,
) -> anyhow::Result<PipeConnection> {
    let name = pipe_name(profile_name, pane_id);
    if let Ok(connection) = PipeConnection::connect(&name) {
        return Ok(connection);
    }

    spawn_detached_holder(profile_name, pane_id, &program, &args, cwd.as_deref(), cursor_shape.as_deref(), scrollback)?;

    for attempt in 0..CONNECT_RETRY_ATTEMPTS {
        match PipeConnection::connect(&name) {
            Ok(connection) => return Ok(connection),
            Err(_) if attempt + 1 < CONNECT_RETRY_ATTEMPTS => std::thread::sleep(CONNECT_RETRY_DELAY),
            Err(err) => return Err(err),
        }
    }
    anyhow::bail!("could not connect to holder for pane {pane_id:?} after spawning it")
}

/// Spawns a fully detached instance of this SAME binary, in `--holder`
/// mode, so it outlives this RELAY process (and thus outlives Som itself —
/// see `crate::server`'s doc comment for what the holder does once
/// running). Uses ONLY `DETACHED_PROCESS`, no `CREATE_NEW_PROCESS_GROUP`/
/// `CREATE_BREAKAWAY_FROM_JOB` — this exact combination was already proven
/// to work (and the alternative proven to fail with `ERROR_ACCESS_DENIED`)
/// by manual testing in the OLD architecture's `som_tmux_client.rs`
/// (`spawn_detached_server`), which this replaces; see that function's
/// history in `project_som_tmux` memory for why.
#[cfg(target_os = "windows")]
fn spawn_detached_holder(
    profile_name: &str,
    pane_id: &str,
    program: &str,
    args: &[String],
    cwd: Option<&str>,
    cursor_shape: Option<&str>,
    scrollback: Option<usize>,
) -> anyhow::Result<()> {
    use std::os::windows::process::CommandExt;

    const DETACHED_PROCESS: u32 = 0x0000_0008;
    // `DETACHED_PROCESS` alone means "don't inherit the parent's console",
    // NOT "don't create one" — without also passing `CREATE_NO_WINDOW`,
    // Windows still allocates a brand-new (visible, briefly flashing)
    // console window for this process, since a normal console-subsystem
    // binary (which `som-tmux.exe` is) otherwise always gets one.
    // Confirmed as a real, visible regression report: a `cmd`-looking
    // window flashing every time a `tmux: true` tab is opened, including
    // purely local ones — this HOLDER spawn happens on every such tab, not
    // just remote/ssh ones.
    const CREATE_NO_WINDOW: u32 = 0x0800_0000;

    let mut command = std::process::Command::new(std::env::current_exe()?);
    command
        .arg("--holder")
        .arg("--profile")
        .arg(profile_name)
        .arg("--pane-id")
        .arg(pane_id)
        .arg("--program")
        .arg(program);
    if let Some(cwd) = cwd {
        command.arg("--cwd").arg(cwd);
    }
    if let Some(cursor_shape) = cursor_shape {
        command.arg("--cursor-shape").arg(cursor_shape);
    }
    if let Some(scrollback) = scrollback {
        command.arg("--scrollback").arg(scrollback.to_string());
    }
    if !args.is_empty() {
        command.arg("--");
        command.args(args);
    }
    command
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .creation_flags(DETACHED_PROCESS | CREATE_NO_WINDOW)
        .spawn()?;
    Ok(())
}

/// Unix equivalent of the Windows `DETACHED_PROCESS` spawn above — same
/// goal (a HOLDER that outlives this RELAY, and thus outlives Som itself),
/// different mechanism: `setsid()` in the child (via `pre_exec`, run after
/// `fork()` but before `exec()`) detaches it from this process's controlling
/// terminal/session, so it isn't sent SIGHUP when Som's own session ends.
/// Just one `fork()`, not the classic double-fork daemon pattern — that
/// second fork exists specifically to guarantee the daemon can never
/// re-acquire a controlling terminal, which doesn't matter here (the
/// HOLDER never opens a tty of its own; its only I/O is the domain socket
/// and the shell's own PTY, both unrelated to any controlling terminal).
/// Not waiting on the child leaves it parentless once THIS process exits,
/// which is fine on Unix (it gets reparented to init/launchd, same as any
/// orphaned process) — no zombie risk since nothing here ever calls
/// `waitpid` on it and nothing needs to.
#[cfg(unix)]
fn spawn_detached_holder(
    profile_name: &str,
    pane_id: &str,
    program: &str,
    args: &[String],
    cwd: Option<&str>,
    cursor_shape: Option<&str>,
    scrollback: Option<usize>,
) -> anyhow::Result<()> {
    use std::os::unix::process::CommandExt;

    let mut command = std::process::Command::new(std::env::current_exe()?);
    command
        .arg("--holder")
        .arg("--profile")
        .arg(profile_name)
        .arg("--pane-id")
        .arg(pane_id)
        .arg("--program")
        .arg(program);
    if let Some(cwd) = cwd {
        command.arg("--cwd").arg(cwd);
    }
    // Read from THIS process's (the RELAY's) own environment — for an SSH
    // `tmux: true` profile, the RELAY itself is what `ssh host
    // ~/.local/bin/som-tmux ...` spawned, so sshd has already set
    // `$SSH_CLIENT` on it to the real connecting client's IP. See
    // `protocol::ssh_client_id`'s doc comment for why this is what
    // `kill_orphaned_holders` scopes cleanup to.
    if let Some(client_id) = som_tmux::protocol::ssh_client_id() {
        command.arg("--client-id").arg(client_id);
    }
    if let Some(cursor_shape) = cursor_shape {
        command.arg("--cursor-shape").arg(cursor_shape);
    }
    if let Some(scrollback) = scrollback {
        command.arg("--scrollback").arg(scrollback.to_string());
    }
    if !args.is_empty() {
        command.arg("--");
        command.args(args);
    }
    unsafe {
        command.pre_exec(|| {
            // SAFETY: `setsid()` is async-signal-safe and the only thing
            // done here between fork and exec — no allocation, no locking,
            // exactly what `pre_exec`'s safety contract requires.
            if libc::setsid() == -1 {
                return Err(std::io::Error::last_os_error());
            }
            Ok(())
        });
    }
    command
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn()?;
    Ok(())
}

/// Drops any `\n` that immediately follows a `\r` — see the call site's doc
/// comment in `run()` for the full explanation of why this is needed at
/// all (Windows ConPTY's own CR-to-CRLF input normalization happening
/// TWICE across this architecture's two ConPTY layers). `last_byte_was_cr`
/// is carried across calls (not reset per-chunk) so a `\r`/`\n` split
/// across two separate `read()` calls — entirely possible depending on how
/// Som's PTY buffers keystrokes — is still caught.
fn strip_cr_induced_lf(chunk: &[u8], last_byte_was_cr: &mut bool) -> Vec<u8> {
    let mut filtered = Vec::with_capacity(chunk.len());
    for &byte in chunk {
        if byte == b'\n' && *last_byte_was_cr {
            *last_byte_was_cr = false;
            continue; // drop the CR-induced LF, don't forward it
        }
        *last_byte_was_cr = byte == b'\r';
        filtered.push(byte);
    }
    filtered
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn settles_immediately_when_the_first_two_reads_already_agree_on_a_real_size() {
        let mut readings = vec![(80, 24), (80, 24), (80, 24)].into_iter();
        let size = settle_from(10, || readings.next());
        assert_eq!(size, (80, 24));
    }

    #[test]
    fn waits_past_a_transient_placeholder_reading_before_settling() {
        // Placeholder, then a real size that repeats — the real bug this
        // whole mechanism exists for (see `settled_initial_size`'s doc
        // comment): the FIRST reading is the DEBUG_TERMINAL_WIDTH/HEIGHT
        // placeholder before Som's real GPUI layout pass has run.
        let mut readings = vec![PLACEHOLDER_SIZE, (171, 52), (171, 52)].into_iter();
        let size = settle_from(10, || readings.next());
        assert_eq!(size, (171, 52));
    }

    #[test]
    fn never_treats_a_repeating_placeholder_as_settled_even_if_it_never_changes() {
        // The WSL-specific failure mode this fix targets: the placeholder
        // can repeat for far longer than a naive "N consecutive identical
        // reads" check would tolerate, because of the extra Windows ConPTY
        // -> wsl.exe -> Linux pty translation hop. Every single reading
        // here is the placeholder — `settle_from` must never lock onto it
        // as "stable", no matter how many attempts it's given.
        let size = settle_from(50, || Some(PLACEHOLDER_SIZE));
        assert_eq!(
            size, PLACEHOLDER_SIZE,
            "falls back to the placeholder once attempts run out (nothing better was ever read), \
             but must not exit EARLY just because the placeholder repeated"
        );
    }

    #[test]
    fn a_real_size_arriving_only_after_many_placeholder_reads_still_wins() {
        // Simulates the actual WSL timing: several placeholder reads (the
        // extra translation hop's latency), then the real size shows up
        // and stabilizes — this must be picked up, not abandoned because
        // `max_attempts` was tuned for the faster local case.
        let mut readings = vec![PLACEHOLDER_SIZE; 20]
            .into_iter()
            .chain(vec![(189, 50), (189, 50)])
            .into_iter();
        let size = settle_from(30, || readings.next());
        assert_eq!(size, (189, 50));
    }

    #[test]
    fn a_size_that_keeps_changing_falls_back_to_the_last_reading_once_attempts_run_out() {
        // A real, still-in-progress drag-resize never producing two
        // matching reads within the attempt budget — falls back to
        // whatever was last seen rather than hanging forever (the
        // resize-poll thread will correct it soon after anyway).
        let mut readings = vec![(100, 30), (120, 35), (140, 40), (160, 45)]
            .into_iter()
            .chain(std::iter::repeat((160, 45)));
        let size = settle_from(3, || readings.next());
        assert_eq!(size, (160, 45));
    }

    #[test]
    fn strips_lf_immediately_after_cr() {
        let mut last_byte_was_cr = false;
        let out = strip_cr_induced_lf(b"\r\n", &mut last_byte_was_cr);
        assert_eq!(out, b"\r");
    }

    #[test]
    fn keeps_a_lone_cr_with_no_following_lf() {
        let mut last_byte_was_cr = false;
        let out = strip_cr_induced_lf(b"\r", &mut last_byte_was_cr);
        assert_eq!(out, b"\r");
        assert!(last_byte_was_cr, "state must remember the trailing CR for a split read");
    }

    #[test]
    fn keeps_a_lone_lf_with_no_preceding_cr() {
        let mut last_byte_was_cr = false;
        let out = strip_cr_induced_lf(b"\n", &mut last_byte_was_cr);
        assert_eq!(out, b"\n", "a bare LF (e.g. from a real multi-line paste) must NOT be dropped");
    }

    #[test]
    fn catches_a_cr_lf_split_across_two_reads() {
        let mut last_byte_was_cr = false;
        let first = strip_cr_induced_lf(b"\r", &mut last_byte_was_cr);
        let second = strip_cr_induced_lf(b"\n", &mut last_byte_was_cr);
        assert_eq!(first, b"\r");
        assert!(second.is_empty(), "the LF arriving in a SEPARATE read right after a CR must still be dropped");
    }

    #[test]
    fn only_drops_the_lf_directly_after_a_cr_not_later_ones() {
        // "\r\n\n" -> the first \n is CR-induced (dropped), the second \n
        // is its own real keystroke (kept) — e.g. Enter followed by a
        // genuine blank-line paste.
        let mut last_byte_was_cr = false;
        let out = strip_cr_induced_lf(b"\r\n\n", &mut last_byte_was_cr);
        assert_eq!(out, b"\r\n");
    }

    #[test]
    fn preserves_ordinary_text_with_no_cr_or_lf_untouched() {
        let mut last_byte_was_cr = false;
        let out = strip_cr_induced_lf(b"echo hello", &mut last_byte_was_cr);
        assert_eq!(out, b"echo hello");
    }

    #[test]
    fn a_real_typed_command_followed_by_enter_keeps_its_text_and_drops_only_the_induced_lf() {
        let mut last_byte_was_cr = false;
        let out = strip_cr_induced_lf(b"echo write-after-idle-marker\r\n", &mut last_byte_was_cr);
        assert_eq!(out, b"echo write-after-idle-marker\r");
    }
}
