use serde::{Deserialize, Serialize};

/// One pipe/HOLDER PER PANE (not per profile) — see `project_som_tmux`
/// memory, "Обновление 17": the earlier design multiplexed several panes'
/// sessions over one profile-wide pipe using a `session_id` field inside
/// every message. That's gone now — since `som-tmux-server` no longer
/// speaks a structured protocol to Som at all (it's a transparent ANSI
/// relay, see `crate::redraw`), there's no client-side session registry
/// to multiplex against either. `pane_id` is generated by Som itself
/// (before ever spawning `som-tmux-server`) and passed as a `--pane-id`
/// argument, the same way on both first creation and restore — the server
/// never invents an id and hands it back the way it used to with
/// `SessionCreated`. `pane_id` (a UUID) is globally unique on its own, so
/// the pipe name doesn't need the profile name folded in for uniqueness —
/// it's kept as a parameter anyway purely so pipe names stay
/// human-readable in diagnostics (`tasklist`, pipe enumeration tools).
pub fn pipe_name(profile_name: &str, pane_id: &str) -> String {
    let sanitize = |s: &str| -> String {
        s.chars()
            .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
            .collect()
    };
    format!(r"\\.\pipe\som-tmux-{}-{}", sanitize(profile_name), sanitize(pane_id))
}

/// RELAY -> HOLDER: input coming from Som's own PTY (whatever the user
/// typed) gets forwarded verbatim, plus the couple of control events a
/// terminal needs to convey out-of-band from plain bytes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RelayInput {
    /// Raw bytes read from Som's side of the RELAY's own PTY — keystrokes,
    /// paste, anything the user's terminal client sends. Forwarded
    /// byte-for-byte into the real shell's PTY on the HOLDER side.
    Bytes(Vec<u8>),
    Resize { cols: u16, rows: u16 },
    /// Explicit "tab closed via UI" — kills the real shell process for
    /// good, as opposed to the RELAY simply disconnecting (which leaves
    /// the HOLDER and its shell running for a later reattach). Mirrors the
    /// detach-vs-kill semantics from the old protocol's `CloseSession`.
    Close,
}

/// HOLDER -> RELAY: what the RELAY writes straight to its own stdout (the
/// PTY Som is reading from) with no further interpretation — plain ANSI
/// bytes generated by `crate::redraw::Redrawer`, ready for Som's own
/// unmodified terminal parser.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum HolderOutput {
    /// ANSI bytes to write to the RELAY's stdout verbatim. The very first
    /// one after a connection is accepted is always a full redraw (see
    /// `Redrawer::new`'s doc comment); every one after that is an
    /// incremental diff against what was already sent.
    Bytes(Vec<u8>),
    /// The real shell process exited — the RELAY should exit too (nothing
    /// left to proxy). Distinct from a HOLDER-initiated disconnect for any
    /// other reason (which the RELAY treats as "connection lost, nothing
    /// more to do" without necessarily needing to know why).
    ShellExited,
}
