//! RELAY side of the transparent-PTY-proxy architecture — see
//! `project_som_tmux` memory ("Обновление 16"-19) for the full design.
//!
//! This is the thin process Som itself spawns directly into its own PTY:
//! from Som's point of view it's just "the shell command" for a `tmux:
//! true` profile — Som's `TerminalElement`/`TerminalView` are completely
//! unaware anything unusual is happening. This process's own stdin/stdout
//! ARE the PTY Som created for it. It connects to the long-lived HOLDER
//! (spawning one if none exists yet for this pane) over a named pipe and
//! simply shuttles bytes: whatever Som's PTY sends on this process's stdin
//! (keystrokes) goes to the HOLDER as `RelayInput::Bytes`; whatever the
//! HOLDER sends back (`HolderOutput::Bytes`, plain ANSI generated by
//! `crate::redraw`) gets written straight to this process's own stdout,
//! which is what Som's terminal parser actually reads.

use som_tmux_server::pipe::PipeConnection;
use som_tmux_server::protocol::{HandshakeInfo, HolderOutput, RelayInput, pipe_name};
use std::io::{Read, Write};
use std::sync::Arc;
use std::time::Duration;

const CONNECT_RETRY_ATTEMPTS: u32 = 20;
const CONNECT_RETRY_DELAY: Duration = Duration::from_millis(100);

/// Runs the RELAY: connects to (or spawns) the HOLDER for this pane, then
/// blocks for the lifetime of the connection, shuttling bytes both ways.
/// Returns once the HOLDER disconnects or the shell it holds exits — at
/// that point there's nothing left for this process to proxy, so `main`
/// just lets it exit (Som sees its PTY's child process end, same as any
/// other shell exiting).
pub fn run(
    profile_name: &str,
    pane_id: &str,
    program: String,
    args: Vec<String>,
    cwd: Option<String>,
    cursor_shape: Option<String>,
    scrollback: Option<usize>,
) -> anyhow::Result<()> {
    let connection = Arc::new(connect_or_become_holder(profile_name, pane_id, program, args, cwd, cursor_shape, scrollback)?);

    // Handshake first, before anything else on this connection — see
    // `protocol::HandshakeInfo`'s doc comment. The relay speaks first here;
    // `crate::server::handle_relay` is the side that waits for it.
    //
    // What happens with a MISMATCHED version/platform: right now, just
    // logged, not acted on — this relay proxies to whatever holder answers
    // regardless. The actual "copy a newer binary over / restart a live
    // holder if none of its panes are busy" policy from `project_som_tmux`
    // memory ("Обновление 19"/"21") needs machinery this crate doesn't have
    // yet (comparing against Som's OWN bundled version, deciding whether to
    // overwrite a file out from under a running process, checking for live
    // child processes under the shell) — deliberately NOT bolted on here
    // half-finished; the handshake EXCHANGE is the prerequisite this adds,
    // the DECISION is future work.
    send(&connection, &RelayInput::Handshake(HandshakeInfo::current()))?;
    match read_holder_message(&connection)? {
        HolderOutput::Handshake(info) => {
            log::info!(
                "holder handshake: version={:?} os={:?} arch={:?}",
                info.version, info.os, info.arch
            );
        }
        other => anyhow::bail!("expected Handshake as the first message from a holder, got {other:?}"),
    }

    // Sends the current pane size right after the handshake, before
    // anything else — `crate::server::handle_relay` deliberately waits for
    // exactly this one message before its first full redraw (see that
    // function's doc comment), so a (re)attaching pane never has to visibly
    // jump from whatever size the session happened to be at to its actual
    // current size. Always sent (never skipped), even when `current_size()`
    // can't read a real size (falls back to `SessionBounds::default()`'s
    // 80x24) — the HOLDER unconditionally waits for exactly one message
    // here, so this side must unconditionally send exactly one.
    let initial_size = crate::term_size::current_size().unwrap_or((80, 24));
    send(&connection, &RelayInput::Resize { cols: initial_size.0, rows: initial_size.1 })?;

    let reader_connection = connection.clone();
    let writer_thread = std::thread::spawn(move || -> anyhow::Result<()> {
        loop {
            let message = read_holder_message(&reader_connection)?;
            match message {
                HolderOutput::Bytes(bytes) => {
                    std::io::stdout().write_all(&bytes)?;
                    std::io::stdout().flush()?;
                }
                HolderOutput::ShellExited => return Ok(()),
                // Only expected once, handled above before this loop
                // starts — a second one mid-connection is a protocol
                // violation from the holder, not something to crash the
                // whole relay over.
                HolderOutput::Handshake(_) => {
                    log::warn!("received an unexpected second Handshake mid-connection, ignoring it");
                }
            }
        }
    });

    // Polls this process's own stdout (Som's PTY, resized whenever Som
    // resizes the pane/window) for size changes and forwards them to the
    // HOLDER — see `crate::term_size`'s module doc comment for why this is
    // a poll rather than an event subscription, and `project_som_tmux`
    // memory ("Обновление 20") for why this was missing entirely before:
    // the HOLDER's session used to be permanently stuck at its initial
    // hardcoded 80x24, which is the root cause of both "the terminal
    // doesn't fill the pane" and (less obviously) stray-looking artifacts
    // after the shell scrolls, since Som's own `TerminalElement` renders at
    // the REAL pane size while every escape code the HOLDER generated was
    // computed against a completely different, wrong screen width.
    let resize_connection = connection.clone();
    let resize_thread = std::thread::spawn(move || {
        // Seeded with the size already sent above, so this loop's first
        // tick doesn't immediately re-send an identical Resize.
        let mut last_size = initial_size;
        loop {
            std::thread::sleep(Duration::from_millis(250));
            let Some((cols, rows)) = crate::term_size::current_size() else { continue };
            if last_size == (cols, rows) {
                continue;
            }
            last_size = (cols, rows);
            if send(&resize_connection, &RelayInput::Resize { cols, rows }).is_err() {
                return; // holder gone — writer_thread/stdin loop will notice too
            }
        }
    });

    // Reads Som's own PTY input (whatever the user types) off this
    // process's stdin and forwards it to the HOLDER. Runs on the main
    // thread/blocks `run` for as long as stdin stays open — Som closing
    // this process's PTY (the whole point of this being a normal PTY
    // child) naturally ends this loop via a read error/EOF.
    let mut buf = [0u8; 4096];
    loop {
        let read = match std::io::stdin().read(&mut buf) {
            Ok(0) => break, // EOF — Som closed its side
            Ok(n) => n,
            Err(_) => break,
        };
        if send(&connection, &RelayInput::Bytes(buf[..read].to_vec())).is_err() {
            break; // holder gone
        }
    }

    // Best-effort: the writer thread's `read_message` will itself error
    // out once this relay's connection handle is dropped at the end of
    // `run` (stdin loop above already broke), so there's nothing more to
    // signal it — just let it wind down on its own rather than blocking
    // this function's return on `join()`. Same reasoning applies to the
    // resize-polling thread — its next `send()` fails once `connection` is
    // gone, ending its loop on its own.
    drop(writer_thread);
    drop(resize_thread);
    Ok(())
}

fn send(connection: &PipeConnection, message: &RelayInput) -> anyhow::Result<()> {
    let payload = serde_json::to_vec(message)?;
    connection.write_message(&payload)?;
    Ok(())
}

fn read_holder_message(connection: &PipeConnection) -> anyhow::Result<HolderOutput> {
    let message = connection.read_message()?;
    Ok(serde_json::from_slice(&message)?)
}

/// Tries to connect to an already-running HOLDER first; if nothing's
/// listening, becomes the HOLDER itself (spawns the real shell in-process
/// and starts serving the pipe) — but that means THIS process would need
/// to keep running as the HOLDER indefinitely, which contradicts it also
/// being Som's own PTY child (Som closing its window would end this
/// process along with the shell inside it, defeating the entire point of
/// detach/reattach). So instead: spawn a SEPARATE, detached process to
/// actually be the HOLDER (reusing the same binary with a `--holder` flag
/// — see `main.rs`), then connect to IT as a normal RELAY. This process
/// itself never becomes a HOLDER directly.
fn connect_or_become_holder(
    profile_name: &str,
    pane_id: &str,
    program: String,
    args: Vec<String>,
    cwd: Option<String>,
    cursor_shape: Option<String>,
    scrollback: Option<usize>,
) -> anyhow::Result<PipeConnection> {
    let name = pipe_name(profile_name, pane_id);
    if let Ok(connection) = PipeConnection::connect(&name) {
        return Ok(connection);
    }

    spawn_detached_holder(profile_name, pane_id, &program, &args, cwd.as_deref(), cursor_shape.as_deref(), scrollback)?;

    for attempt in 0..CONNECT_RETRY_ATTEMPTS {
        match PipeConnection::connect(&name) {
            Ok(connection) => return Ok(connection),
            Err(_) if attempt + 1 < CONNECT_RETRY_ATTEMPTS => std::thread::sleep(CONNECT_RETRY_DELAY),
            Err(err) => return Err(err),
        }
    }
    anyhow::bail!("could not connect to holder for pane {pane_id:?} after spawning it")
}

/// Spawns a fully detached instance of this SAME binary, in `--holder`
/// mode, so it outlives this RELAY process (and thus outlives Som itself —
/// see `crate::server`'s doc comment for what the holder does once
/// running). Uses ONLY `DETACHED_PROCESS`, no `CREATE_NEW_PROCESS_GROUP`/
/// `CREATE_BREAKAWAY_FROM_JOB` — this exact combination was already proven
/// to work (and the alternative proven to fail with `ERROR_ACCESS_DENIED`)
/// by manual testing in the OLD architecture's `som_tmux_client.rs`
/// (`spawn_detached_server`), which this replaces; see that function's
/// history in `project_som_tmux` memory for why.
#[cfg(target_os = "windows")]
fn spawn_detached_holder(
    profile_name: &str,
    pane_id: &str,
    program: &str,
    args: &[String],
    cwd: Option<&str>,
    cursor_shape: Option<&str>,
    scrollback: Option<usize>,
) -> anyhow::Result<()> {
    use std::os::windows::process::CommandExt;

    const DETACHED_PROCESS: u32 = 0x0000_0008;

    let mut command = std::process::Command::new(std::env::current_exe()?);
    command
        .arg("--holder")
        .arg("--profile")
        .arg(profile_name)
        .arg("--pane-id")
        .arg(pane_id)
        .arg("--program")
        .arg(program);
    if let Some(cwd) = cwd {
        command.arg("--cwd").arg(cwd);
    }
    if let Some(cursor_shape) = cursor_shape {
        command.arg("--cursor-shape").arg(cursor_shape);
    }
    if let Some(scrollback) = scrollback {
        command.arg("--scrollback").arg(scrollback.to_string());
    }
    if !args.is_empty() {
        command.arg("--");
        command.args(args);
    }
    command
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .creation_flags(DETACHED_PROCESS)
        .spawn()?;
    Ok(())
}

/// Unix equivalent of the Windows `DETACHED_PROCESS` spawn above — same
/// goal (a HOLDER that outlives this RELAY, and thus outlives Som itself),
/// different mechanism: `setsid()` in the child (via `pre_exec`, run after
/// `fork()` but before `exec()`) detaches it from this process's controlling
/// terminal/session, so it isn't sent SIGHUP when Som's own session ends.
/// Just one `fork()`, not the classic double-fork daemon pattern — that
/// second fork exists specifically to guarantee the daemon can never
/// re-acquire a controlling terminal, which doesn't matter here (the
/// HOLDER never opens a tty of its own; its only I/O is the domain socket
/// and the shell's own PTY, both unrelated to any controlling terminal).
/// Not waiting on the child leaves it parentless once THIS process exits,
/// which is fine on Unix (it gets reparented to init/launchd, same as any
/// orphaned process) — no zombie risk since nothing here ever calls
/// `waitpid` on it and nothing needs to.
#[cfg(unix)]
fn spawn_detached_holder(
    profile_name: &str,
    pane_id: &str,
    program: &str,
    args: &[String],
    cwd: Option<&str>,
    cursor_shape: Option<&str>,
    scrollback: Option<usize>,
) -> anyhow::Result<()> {
    use std::os::unix::process::CommandExt;

    let mut command = std::process::Command::new(std::env::current_exe()?);
    command
        .arg("--holder")
        .arg("--profile")
        .arg(profile_name)
        .arg("--pane-id")
        .arg(pane_id)
        .arg("--program")
        .arg(program);
    if let Some(cwd) = cwd {
        command.arg("--cwd").arg(cwd);
    }
    if let Some(cursor_shape) = cursor_shape {
        command.arg("--cursor-shape").arg(cursor_shape);
    }
    if let Some(scrollback) = scrollback {
        command.arg("--scrollback").arg(scrollback.to_string());
    }
    if !args.is_empty() {
        command.arg("--");
        command.args(args);
    }
    unsafe {
        command.pre_exec(|| {
            // SAFETY: `setsid()` is async-signal-safe and the only thing
            // done here between fork and exec — no allocation, no locking,
            // exactly what `pre_exec`'s safety contract requires.
            if libc::setsid() == -1 {
                return Err(std::io::Error::last_os_error());
            }
            Ok(())
        });
    }
    command
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn()?;
    Ok(())
}
