[package]
name = "som_key"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[[bin]]
name = "som-key"
path = "src/main.rs"

[dependencies]
gpui = { workspace = true, features = ["input-latency-histogram"] }
gpui_platform = { workspace = true, features = ["font-kit", "wayland", "x11"] }
